### ISSUE TITLE
Page scroll offset does not get reset when navigating to a new page.

### ISSUE THREAD

**Issue by swazza** [postmanlabs/postman-docs#2578] opened 2020-08-10 15:15 UTC
How to reproduce - 

- Navigate to `https://learning.postman.com/docs/getting-started/introduction/` 
- In the navigation pane, go to Integrations > Available Integrations > Victor Ops.
- This is what is displayed in the viewport
<img width="1440" alt="Screenshot 2020-08-10 at 8 30 41 PM" src="https://user-images.githubusercontent.com/6040265/89797683-d8398d00-db48-11ea-9a0e-ac66ca91b725.png">

Suggestion - 
- Independent scroll for the navigation pane and the content.

**Comment by tristandenyer** [comment] 2020-08-10 15:55
@swazza I tried to reproduce and each time I got the top of the page when paginating to 'Victorops' page, as expected. (See screenshot below)

<img width="1559" alt="Screen Shot 2020-08-10 at 8 52 42 AM" src="https://user-images.githubusercontent.com/4358288/89803064-333a9800-dae7-11ea-8780-19e83476af2b.png">

As for making the left nav and page content separate scroll mechanisms, we are looking into a site redesign and will be exploring this.

**Comment by swazza** [comment] 2020-08-11 05:04
I am noticing this behaviour on Safari (MacBook & iPad) & Firefox. The scroll behaviour seems to be working fine on Chrome. I should've mentioned this as part of the issue itself.

**Comment by kushal-khare-official** [comment] 2020-11-22 11:25
@swazza I  also tried to reproduce this issue on Firefox 
![ss](https://user-images.githubusercontent.com/62568269/99902375-6ba36200-2ce3-11eb-9760-0b3b2c799e10.png)
and each time I got the top of the page when paginating to 'Victorops' page, as expected. (See screenshot below)

**Comment by jkonrath-postman** [comment] 2021-06-01 16:29
Seems to be working as expected in Safari 14 on both macOS and iOS. Closing this out, but if you can reproduce again, feel free to open a new issue.

**Closed by jkonrath-postman** 2021-06-01 16:29 UTC
