### ISSUE TITLE
Linked Resources returning 404

### ISSUE THREAD

**Issue by hneil33** [postmanlabs/postman-docs#2454] opened 2020-06-11 20:56 UTC
Hello there,

On this "[intro to writing tests - with examples](https://documenter.getpostman.com/view/1559645/RzZFCGFR?version=latest&_ga=2.246455682.741239282.1590518389-1441272340.1587667254)" page, the test scrips and test example pages linked under Resources return a 404.

**Comment by SueSmith** [comment] 2020-06-12 08:55
Thanks for reporting @hneil33! I think this may be a duplicate of #2361

**Comment by loopDelicious** [comment] 2020-09-23 21:38
Yep - fixed with #2361

**Closed by loopDelicious** 2020-09-23 21:38 UTC
