### ISSUE TITLE
Some sidebar elements not clickable

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2411] opened 2020-05-26 18:01 UTC
The `Postman Templates` and `Run in Postman` sections in the sidebar are not clickable to expand and display those pages.

If I remember what content is in those sections, I can search for content on those pages. But currently no way to navigate to those pages.

**Comment by tristandenyer** [comment] 2020-05-26 21:22
Seems to be working for me in Chrome:
<img width="570" alt="Screen Shot 2020-05-26 at 2 21 50 PM" src="https://user-images.githubusercontent.com/4358288/82951569-431cf400-9f5c-11ea-8e75-d65975fb855c.png">

As seen here: https://learning.postman.com/docs/postman-for-publishers/postman-templates/add-templates/

**Comment by SueSmith** [comment] 2020-05-26 23:10
still isn't working for me but it'll depend on screen size, display, what page is open etc rather than specific folders not being clickable in general - this is chrome too
![Screenshot 2020-05-27 at 00 07 17](https://user-images.githubusercontent.com/6666370/82958806-33c69680-9fae-11ea-879e-28792f081e6e.jpg)
(everything under the div isn't clickable)

**Comment by SueSmith** [comment] 2020-05-26 23:12
@tristandenyer if you try a page that makes the nav extend beyond the bottom of the screen e.g. probably docs homepage https://learning.postman.com/docs/postman/launching-postman/introduction/ I'd guess you'll see the issue at the bottom left of your browser window

**Comment by tristandenyer** [comment] 2020-05-27 00:59
Ah, @mclausaudio's latest PR #2413  should fix that. Just needs to be merged in and deployed.

**Comment by ch264** [comment] 2020-06-01 21:55
@joyous-joyce I believe this bug has been fixed. I cannot reproduce it on my machine anymore. Ca n you please double check and let me know so we can close the ticket?

**Comment by loopDelicious** [comment] 2020-06-02 18:15
lgtm

**Comment by ch264** [comment] 2020-06-02 23:08
Thank you @loopDelicious

**Closed by ch264** 2020-06-02 23:08 UTC
